= LinkerScript - What It is ?
== LinkerScript - How to get it

Linker script will using by `ld` tool.
The linker script is default hard code in ld tool.
Can dump the linker script by command bellow

[source,shell]
----
ld --verbose > linkerscript.ld
----

* for example:
** With native gcc in ubuntu could you command like above to dump linker script.

[source,shell]
----
ld --verbose > linkerscript.ld
----

** with cross toolchain , it is similar or it will use a default linker script for chipset support.

=== Compile your source with your customize linker script

by default, linker will use it build/default linker script.
For redirect linker to use your linkerscript.
You must tell you linker that you want to use a specific linker script

Using gcc/Makefile

[source,bash]
----
gcc -c example.c
ld -o prog2 -T my_script.lds example.o
----

by option `-T` will tell linker that it should use the following specific linker script.

Using CMake

[source,cmake]
----
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -T ${CMAKE_SOURCE_DIR}/Scripts/x86_gcc/linkerscript.ld")
----

=== Simple Linker Script

bellow is simple linker script

[source,c]
----
#include <stdio.h>

void this_is_my_main(void){
    int a;
    a++;
}
----

[source,lldb]
----
OUTPUT_FORMAT("elf64-x86-64", "elf64-x86-64",
	      "elf64-x86-64")
OUTPUT_ARCH(i386:x86-64)

ENTRY(this_is_my_main)

SECTIONS
{
   . = 0x8048000;
   text_start = .;
   .text : { *(.text) }
   . = 0x8000000;
    .data_start = .;
   .data : { *(.data) }
   .bss : { *(.bss) }
}
----

compile the example source file with the example linker script by command

[source,shell script]
----
ld -o prog2 -T my_script.lds example.o
----

using command `nm` to get all info about symbol mapping

[source,bash]
----
nm prog2
# return result
0000000008048000 T text_start
0000000008048000 T this_is_my_main
----

by looking at the result from command `nm`, we could see that the symbol `text_start` and `text` the `data` will exist at run time.
the example will not work because of depending on posix lib.
Then switch to default linker script come from `ld`
Customizing the default script by adding `<section>_start = .;` in before each section in linker script for example: `text_start`, `data_start`,`_bss_start`.
using gcc compiler and customized linkerscript

[source,bash]
----
gcc -g example_posix.c -T linkerscript.ld -o example_posix
#nm example_posix
0000000000601040 B __bss_start
0000000000601040 b completed.7697
                 w __cxa_finalize@@GLIBC_2.2.5
0000000000601030 D __data_start
0000000000601030 D data_start
00000000004005f0 t deregister_tm_clones
0000000000400680 t __do_global_dtors_aux
0000000000600de0 t __do_global_dtors_aux_fini_array_entry
0000000000601038 D __dso_handle
0000000000600de8 d _DYNAMIC
0000000000601040 D _edata
0000000000601048 B _end
                 U exit@@GLIBC_2.2.5
00000000004007a4 T _fini
00000000004006c0 t frame_dummy
0000000000600dd8 t __frame_dummy_init_array_entry
0000000000400974 r __FRAME_END__
0000000000601000 d _GLOBAL_OFFSET_TABLE_
                 w __gmon_start__
0000000000400830 r __GNU_EH_FRAME_HDR
0000000000400558 T _init
0000000000600de0 t __init_array_end
0000000000600dd8 t __init_array_start
00000000004007b0 R _IO_stdin_used
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
00000000004007a0 T __libc_csu_fini
0000000000400730 T __libc_csu_init
                 U __libc_start_main@@GLIBC_2.2.5
00000000004006ca T main
                 U printf@@GLIBC_2.2.5
                 U puts@@GLIBC_2.2.5
0000000000400630 t register_tm_clones
00000000004007ad T rodata_start
00000000004005c0 T _start
00000000004005b8 T text_start
0000000000601040 D __TMC_END__
----

[source,text]
----
# run example_posix
./example_posix
## result
First address past:
program text (text_start) 0x4005b8
initialized data (data_start) 0x601030
bss (__bss_start) 0x601040
----

interesting here that the output of `example_posix` and the `nm`  (value of `<section>_start` look like the same. the reason for that is because of Virtual Memory.
So, Linux uses Virtual memory mapping each procecss will create for itself virtual memory mapping will have another post about `virtual memory` to detail about it.
But now we can see that by custom linker script we can identify the segments (text, data, bss) about detail of linker segment it should be in another post about `compile`

